services:

  mysql:
    image: mysql:8
    container_name: indexer_mysql
    ports:
      - "33066:3306"
    command: ["mysqld", "--mysql-native-password=ON"]
    environment:
      MYSQL_LOGGING: true
      MYSQL_DATABASE: prise
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pw
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    secrets:
      - mysql_pw
      - mysql_user
      - mysql_root_pw
    restart: on-failure
    networks:
      custom_net:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  indexer:
    image: prise/indexer:latest
    container_name: indexer
    ports:
      - "9108:9108"
    restart: on-failure
    networks:
      custom_net:
    depends_on:
      - "mysql"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets:
  mysql_pw:
    file: ./db/secrets/mysql_pw
  mysql_user:
    file: ./db/secrets/mysql_user
  mysql_root_pw:
    file: ./db/secrets/mysql_root_pw

networks:
  custom_net:

volumes:
  mysql_data: