package tech.edgx.prise.indexer.config

object Constants {
    const val RUN_MODE_PROPERTY = "run.mode"
    const val LATEST_PRICES_UPDATE_INTERVAL_PROPERTY = "latest.prices.livesync.update.interval.seconds"
    const val START_METRICS_SERVER_PROPERTY = "start.metrics.server"
    const val METRICS_SERVER_PORT_PROPERTY = "metrics.server.port"
    const val APP_DB_URL_PROPERTY = "app.datasource.url"
    const val APP_DB_UNAME_PROPERTY = "app.datasource.username"
    const val APP_DB_PASS_PROPERTY = "app.datasource.password"
    const val APP_DB_DRIVER_PROPERTY = "app.datasource.driver-class-name"
    const val TOKEN_METADATA_SERVICE_MODULE_PROPERTY = "token.metadata.service.module"
    const val CHAIN_DATABASE_SERVICE_MODULE_PROPERTY = "chain.database.service.module"
    const val CARP_DB_URL_PROPERTY = "carp.datasource.url"
    const val CARP_DB_UNAME_PROPERTY = "carp.datasource.username"
    const val CARP_DB_PASS_PROPERTY = "carp.datasource.password"
    const val CARP_DB_DRIVER_PROPERTY = "carp.datasource.driver-class-name"
    const val KOIOS_DATASOURCE_URL_PROPERTY = "koios.datasource.url"
    const val KOIOS_DATASOURCE_APIKEY_PROPERTY = "koios.datasource.apikey"
    const val BLOCKFROST_DATASOURCE_URL_PROPERTY = "blockfrost.datasource.url"
    const val BLOCKFROST_DATASOURCE_APIKEY_PROPERTY = "blockfrost.datasource.apikey"
    const val YACISTORE_DATASOURCE_URL_PROPERTY = "yacistore.datasource.url"
    const val YACISTORE_DATASOURCE_APIKEY_PROPERTY = "yacistore.datasource.apikey"
    const val CNODE_ADDRESS_PROPERTY = "cnode.address"
    const val CNODE_PORT_PROPERTY = "cnode.port"
    const val DEX_CLASSIFIERS_PROPERTY = "dex.classifiers"
    const val START_POINT_TIME_PROPERTY = "start.point.time"
    const val EVENT_PUBLISHING_ENABLED_PROPERTY = "event.publishing.enabled"
    const val MESSAGING_TYPE_PROPERTY = "messaging.type"
    const val MESSAGING_HOST_PROPERTY = "messaging.host"
    const val MESSAGING_PORT_PROPERTY = "messaging.port"
    const val MESSAGING_CHANNEL_PROPERTY = "messaging.channel"
    const val MESSAGING_USERNAME_PROPERTY = "messaging.username"
    const val MESSAGING_PASSWORD_PROPERTY = "messaging.password"
    const val LOG_ENV_PROPERTY = "log.env"
}